version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./db.env
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d


  nats-streaming:
    image: nats-streaming:latest
    container_name: nats_streaming
    ports:
      - "4222:4222"
      - "8222:8222"