version: '3.9'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./db.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats_streaming
    ports:
      - "4222:4222"
      - "8222:8222"